[package]
name = "dmx-control"
version = "0.1.0"
authors = ["Tom Spurling <tom@tspurling.co.uk>"]
edition = "2018"

[dependencies]
dirs = "3.0"
libc = "0.2"
libftdi1-sys = "0.1.0"
safe-ftdi = "0.2.2"
